version: '3.7'

services: 

  memory-social-ui:
    image: tbichse/dvc-calc-ui:1.5-ubuntu
    container_name: memory-social-ui 
    stdin_open: true
    ports: 
      - 8080:80
    depends_on:
      - memory-social-api
  
  memory-social-api:
    image: tbichse/memory-social-api:1.2-ubuntu
    container_name: memory-social-api
    stdin_open: true
    environment:
      NODE_ENV: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports: 
        - 3001:3001
    depends_on:
      - db
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    external:
      name: nginxproxy
