version: '3.7'

services: 

  memory-social-ui:
    image: tbichse/memory-social-ui:1.4-ubuntu
    container_name: memory-social-ui 
    stdin_open: true
    ports: 
      - 8088:80
    depends_on:
      - memory-social-api
  
  memory-social-api:
    image: tbichse/memory-social-api:1.3-ubuntu
    container_name: memory-social-api
    stdin_open: true
    environment:
      NODE_ENV: dev
      DB_HOST: memory-social-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    ports: 
        - 3007:3007
    volumes: 
      - ./images:/app/images
    depends_on:
      - memory-social-db
  
  memory-social-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes: 
      - ./memory-social/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    external:
      name: nginxproxy
